"""3.0 day 2: the genetic toolkit (driver lines -> cell types -> neurons). The table is the real published one; the brains are
the synthetic pack or plain arrays. Nothing here is a biological result."""
from __future__ import annotations

import subprocess
import sys
import zipfile
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from conftest import needs_pack
from kickthefly.lab import genetics

ROOT = Path(__file__).resolve().parent.parent


def test_table_is_the_published_one_with_its_provenance():
    src = genetics.source()
    assert src["license"] == "CC BY 4.0" and src["doi"] == "10.7554/eLife.98405"
    assert len(src["table_sha256"]) == 64
    t = genetics.table()
    assert len(t) > 2000
    assert "SS00727" in t and "DNp01" in t["SS00727"].cell_types
    # the header says where it came from, in the file itself
    head = (ROOT / "kickthefly" / "data" / "driver_lines.yaml").read_text(encoding="utf-8")[:1500]
    assert "Meissner" in head and "CC BY 4.0" in head and "GENERATED by tools/build_driver_lines.py" in head


def test_a_line_name_i_remembered_wrongly_is_not_in_the_table():
    """SS00731 is DNa01 in the table (not the giant fiber): the toolkit reports what the source says, not what anyone remembers."""
    assert genetics.get("SS00731").cell_types == ("DNa01",)
    assert genetics.get("ss00727").name == "SS00727"                 # case-insensitive
    with pytest.raises(genetics.GeneticsError, match="unknown driver line"):
        genetics.get("SS99999999")


def test_every_entry_is_the_sources_own_row_shape():
    """Names are plain line names; qualities are the paper's 1-5 or (one row) the source's own 'Control'; the citation is a DOI or
    the source's own 'in prep' note. Nothing here is written by hand."""
    import re

    t = genetics.table()
    assert all(re.fullmatch(r"[A-Za-z0-9_\-]+", ln.name) and ln.cell_types for ln in t.values())
    assert {ln.quality for ln in t.values()} <= {"1", "2", "3", "4", "5", "Control"}
    assert all(ln.doi.startswith("10.") or "in prep" in ln.doi or ln.doi == "" for ln in t.values())


def test_matching_is_exact_and_never_guessed():
    types = np.array(["DNp01", "DNp01", "DNp010", "LPLC2", "LPLC2", "LPLC2", ""])
    m = genetics.match("SS00727", types)
    assert m.matched == {"DNp01": 2} and m.neurons == 2 and not m.unmatched
    assert list(m.rows) == [0, 1]                                    # DNp010 is a different type: no prefix matching
    none = genetics.match("SS00731", types)                          # DNa01 is not in these types
    assert none.neurons == 0 and none.unmatched == ["DNa01"]


def test_line_spec_in_rows_of_and_clear_errors():
    from kickthefly.core import simcore

    br = SimpleNamespace(types=np.array(["DNp01", "DNp01", "DNa01", "LPLC2"]), n=4)
    assert list(simcore.rows_of(br, "line:SS00727")) == [0, 1]
    assert list(simcore.rows_of(br, "line:SS00727,SS00731")) == [0, 1, 2]
    with pytest.raises(ValueError, match="selects no neurons"):
        simcore.rows_of(SimpleNamespace(types=np.array(["X"]), n=1), "line:SS00727")
    with pytest.raises(ValueError, match="unknown driver line"):
        simcore.rows_of(br, "line:NOPE123")
    with pytest.raises(ValueError, match="at least one"):
        simcore.rows_of(br, "line:")


def test_off_target_says_no_more_than_the_paper():
    L = genetics.Line
    lvl = lambda q, n=1: genetics.off_target(L("x", q, "N", "No", "No", tuple("ab"[:n])))   # noqa: E731
    assert lvl("1")[0] == "minimal" and "occasional weak expression" in lvl("1")[1]
    assert lvl("2", 1)[0] == "some" and "off-target" in lvl("2", 1)[1]
    assert "off-target" not in lvl("2", 2)[1]
    assert lvl("3")[0] == "yes" and lvl("4")[0] == "weak" and lvl("5")[0] == "unstable"
    level, text = lvl("Clean Brain only")
    assert level == "unknown" and "nothing is claimed" in text


def test_describe_gives_line_types_count_and_the_note():
    types = np.array(["DNp01"] * 2 + ["PFNa"] * 5)
    d = genetics.describe("SS00043", types)                          # PFNa, quality 1
    assert d["cell_types"] == ["PFNa"] and d["matched"] == {"PFNa": 5} and d["neurons"] == 5
    assert d["off_target"] == "minimal" and d["cite"] and d["doi"]


def test_search_orders_line_name_before_cell_type_hits():
    r = genetics.search("SS00727")
    assert r[0].name == "SS00727"
    names = [ln.name for ln in genetics.search("DNp01")]
    assert "SS00727" in names and "SS02299" in names
    assert genetics.search("") == [] and genetics.lines_for_type("DNp01")


def test_laser_target_accepts_a_line():
    from kickthefly.lab.laser import LaserState

    br = SimpleNamespace(types=np.array(["DNp01", "DNp01", "X"]), n=3)
    ls = LaserState(target_type="line:SS00727")
    assert list(ls.resolve_target_rows(br)) == [0, 1]
    bad = LaserState(target_type="line:NOPE123")
    assert len(bad.resolve_target_rows(SimpleNamespace(types=np.array(["X"]), n=1))) == 0     # no crash, selects nothing


def _tiny_xlsx(path: Path, rows: list[dict]) -> None:
    cols = "ABCDEFGHIJKLMNO"
    strings, sheet = [], []

    def s(v):
        if v not in strings:
            strings.append(v)
        return strings.index(v)

    for r, row in enumerate(rows, 1):
        cells = "".join(f'<c r="{c}{r}" t="s"><v>{s(v)}</v></c>' for c, v in row.items())
        sheet.append(f'<row r="{r}">{cells}</row>')
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("xl/sharedStrings.xml", "<sst>" + "".join(f"<si><t>{x}</t></si>" for x in strings) + "</sst>")
        z.writestr("xl/worksheets/sheet1.xml", "<worksheet><sheetData>" + "".join(sheet) + "</sheetData></worksheet>")
        z.writestr("xl/workbook.xml", "<workbook/>")


def test_the_builder_reads_the_published_layout_and_refuses_another(tmp_path):
    sys.path.insert(0, str(ROOT / "tools"))
    import build_driver_lines as b

    head = {"A": "Line", "B": "Adult/\r\nLarval", "E": "Quality", "F": "Sex difference", "G": "VNC only", "H": "Brain only",
            "I": "DOI to cite", "J": "First author(s) & year", "L": "Cell types"}
    good = tmp_path / "t.xlsx"
    _tiny_xlsx(good, [head,
                      {"A": "SS1", "B": "Adult", "E": "1", "F": "N", "G": "No", "H": "No", "I": "10.1/x", "J": "A; 2020", "L": "DNp01, MDN"},
                      {"A": "SS2", "B": "Larval", "E": "1", "L": "KC"},
                      {"A": "SS3", "B": "Adult", "E": "2", "L": ""}])
    lines, sha = b.build(good)
    assert [d["line"] for d in lines] == ["SS1"] and lines[0]["cell_types"] == ["DNp01", "MDN"] and len(sha) == 64
    out = tmp_path / "driver_lines.yaml"
    b.write(lines, sha, out)
    assert "SS1" in out.read_text(encoding="utf-8")
    bad = tmp_path / "bad.xlsx"
    _tiny_xlsx(bad, [dict(head, L="Something else")])
    with pytest.raises(SystemExit, match="unexpected table layout"):
        b.build(bad)


def test_builder_output_is_what_ships():
    """The shipped file carries a table hash; the builder is the only way it is meant to change."""
    src = genetics.source()
    text = (ROOT / "kickthefly" / "data" / "driver_lines.yaml").read_text(encoding="utf-8")
    assert src["table_sha256"] in text and text.count("\n  - {") == len(genetics.table())


@needs_pack
def test_on_the_real_adult_pack_the_giant_fiber_lines_select_its_two_neurons():
    from kickthefly.core import simcore

    g = simcore.pack()[0]
    types = np.asarray(g.type).astype(str)
    for line in ("SS00727", "SS02299"):
        m = genetics.match(line, types)
        assert m.matched == {"DNp01": 2}
    cov = genetics.coverage(types)
    assert cov["lines_with_a_match"] > 1000 and cov["cell_type_names_matched"] > 800
    m = genetics.match("OL0047B", types)
    assert list(m.matched) == ["LPLC2"] and m.neurons == int((types == "LPLC2").sum())
