"""Build kickthefly/data/driver_lines.yaml from the split-GAL4 resource's published table (run by a developer, never by
the game: the game makes no network requests for this).

Source: Meissner GW, Vannan A, ... FlyLight Project Team. "A split-GAL4 driver line resource for Drosophila neuron types." eLife 2025;13:RP98405. doi:10.7554/eLife.98405
Article and Figure 1-source data 1 are licensed CC BY 4.0. The table lists each line, the cell types the authors say it
labels, and a quality score of its expression (how clean it is). Only adult lines that name at least one cell type are kept.
The table names cell types with the light-microscopy literature's names (hemibrain / FlyWire / MANC style); this file keeps
them exactly as written. Matching them to MaleCNS types is done by exact name at run time (lab/genetics.py) and never guessed.

    python tools/build_driver_lines.py [--xlsx FILE]     # downloads Figure 1-source data 1 unless --xlsx is given
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
import urllib.request
import zipfile
from datetime import date
from pathlib import Path

URL = "https://cdn.elifesciences.org/articles/98405/elife-98405-fig1-data1-v2.xlsx"
OUT = Path(__file__).resolve().parent.parent / "kickthefly" / "data" / "driver_lines.yaml"


def read_sheet(path: Path) -> list[dict]:
    """Rows of the first sheet of an .xlsx as {column letter: text}. Standard library only."""
    z = zipfile.ZipFile(path)
    strings = []
    if "xl/sharedStrings.xml" in z.namelist():
        for si in re.findall(r"<si>(.*?)</si>", z.read("xl/sharedStrings.xml").decode("utf-8"), re.S):
            strings.append(html.unescape("".join(re.findall(r"<t[^>]*>(.*?)</t>", si, re.S))))
    sheet = z.read("xl/worksheets/sheet1.xml").decode("utf-8")
    rows = []
    for r in re.findall(r"<row [^>]*>(.*?)</row>", sheet, re.S):
        row = {}
        for m in re.finditer(r'<c r="([A-Z]+)\d+"([^>]*?)(?:/>|>(.*?)</c>)', r, re.S):
            col, attr, body = m.groups()
            if body is None:
                continue
            v = re.search(r"<v>(.*?)</v>", body, re.S)
            if v is None:
                t = re.search(r"<t[^>]*>(.*?)</t>", body, re.S)
                val = html.unescape(t.group(1)) if t else ""
            else:
                val = v.group(1)
                if 't="s"' in attr:
                    val = strings[int(val)]
            row[col] = val.strip()
        rows.append(row)
    return rows


def build(xlsx: Path) -> tuple[list[dict], str]:
    rows = read_sheet(xlsx)
    head = rows[0]
    want = {"Line": "A", "Adult/\r\nLarval": "B", "Quality": "E", "Sex difference": "F", "VNC only": "G", "Brain only": "H",
            "DOI to cite": "I", "First author(s) & year": "J", "Cell types": "L"}
    for name, col in want.items():
        if head.get(col) != name:
            raise SystemExit(f"unexpected table layout: column {col} is {head.get(col)!r}, expected {name!r}")
    lines = []
    for r in rows[1:]:
        if r.get("B") != "Adult" or not r.get("L") or not r.get("A"):
            continue
        types = [t.strip() for t in re.split(r"[,;]", r["L"]) if t.strip()]
        lines.append(dict(line=r["A"], quality=r.get("E", ""), sex_difference=r.get("F", ""), vnc_only=r.get("G", ""),
                          brain_only=r.get("H", ""), cell_types=types, doi=r.get("I", ""), cite=r.get("J", "")))
    lines.sort(key=lambda d: d["line"])
    return lines, hashlib.sha256(Path(xlsx).read_bytes()).hexdigest()


def write(lines: list[dict], sha: str, out: Path = OUT) -> None:
    head = f"""# Driver lines -> cell types, for Lab > Genetic toolkit. GENERATED by tools/build_driver_lines.py; do not edit by hand.
#
# Source : Meissner et al. 2025, "A split-GAL4 driver line resource for Drosophila neuron types", eLife 13:RP98405,
#          doi:10.7554/eLife.98405, Figure 1-source data 1 ({URL})
# License: CC BY 4.0 (the article and its source data). Redistributed here with attribution, reduced to the columns below.
# File   : SHA-256 of the downloaded table {sha}
# Built  : {date.today().isoformat()}
# What it is: the authors' own list of which cell types each adult split-GAL4 line labels, with their expression-quality
#          score (1 = one cell type, occasional weak expression elsewhere; 2 = two cell types; 3 = three or more; 4 = weak or
#          variable labeling; 5 = not stabilized; other values are kept as written). Cell types are named as the paper
#          names them. They are NOT MaleCNS body annotations: a name is matched to the game's connectome only when it is
#          spelled exactly like a MaleCNS type, and the rest are kept and reported as unmatched.
# Not included: GAL4 (non-split) lines, larval lines, intersectional or LexA lines, and lines whose cell-type cell is empty.
format: 1
source:
  title: "A split-GAL4 driver line resource for Drosophila neuron types"
  authors: "Geoffrey W Meissner, Allison Vannan ... FlyLight Project Team"
  journal: "eLife 13:RP98405 (2025)"
  doi: "10.7554/eLife.98405"
  license: "CC BY 4.0"
  table_url: "{URL}"
  table_sha256: "{sha}"
  built: "{date.today().isoformat()}"
lines:
"""
    body = "".join("  - " + json.dumps(d, ensure_ascii=False, separators=(", ", ": ")) + "\n" for d in lines)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(head + body, encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--xlsx", type=Path, help="a local copy of Figure 1-source data 1 (downloaded when omitted)")
    args = ap.parse_args(argv)
    path = args.xlsx
    if path is None:
        path = Path("/tmp") / "elife-98405-fig1-data1-v2.xlsx"
        print(f"downloading {URL}")
        urllib.request.urlretrieve(URL, path)
    lines, sha = build(path)
    write(lines, sha)
    print(f"wrote {len(lines)} adult lines to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
